[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.4.11"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[profile.release]
codegen-units = 1

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.30", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
itertools = "0.11"
paste = "1.0"
quork = "0.4"
rayon = "1.7"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sfsu-derive = { path = "./sfsu-derive" }
strum = { version = "0.25", features = ["derive"] }
