[package]
description = "Stupid Fast Scoop Utils"
edition = "2021"
name = "sfsu"
publish = { workspace = true }
version = { workspace = true }

[workspace]
members = ["crates/*"]
package.license = "Apache-2.0"
package.publish = false
package.version = "1.10.0"

[workspace.dependencies]
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
quork = "0.6"

[[bench]]
harness = false
name = "searching"

[[bench]]
harness = false
name = "serde"

[profile.release]
codegen-units = 1
lto = true

[features]
default = []
# Breaking changes are locked behind this feature flag
v2 = ["sprinkles/v2"]

[dependencies]
anyhow = "1.0"
bat = "0.24"
clap = { version = "4.5", features = ["derive"] }
git2 = "0.18"
human-panic = "1.2"
indicatif = { version = "0.17", features = ["improved_unicode", "rayon"] }
itertools = "0.12"
log = { version = "0.4", features = ["std"] }
open = "5.1"
owo-colors = { workspace = true }
parking_lot = "0.12"
quork = { workspace = true }
rayon = "1.10"
regex = "1.10"
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "crates/derive" }
shadow-rs = "0.27"
sprinkles = { version = "1", path = "crates/sprinkles" }

[dev-dependencies]
chrono = ">=0.4.37"
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
shadow-rs = "0.27"
winres = "0.1"
