[package]
description = "Stupid Fast Scoop Utils"
edition     = "2021"
name        = "sfsu"
version     = "1.9.1"

[workspace]
members = ["crates/*"]

[[bench]]
harness = false
name    = "searching"

[profile.release]
codegen-units = 1
lto           = true

[features]
default        = ["info-difftrees"]
info-difftrees = []
# Breaking changes are locked behind this feature flag
v2 = []

[dependencies]
anyhow = "1.0"
cfg-if = "1.0"
chrono = { version = ">=0.4.20", features = [
    "clock",
    "serde",
    "std",
], default-features = false }
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
const-str = { version = "0.5", features = ["all"] }
const_format = { version = "0.2.32", features = [] }
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
git2 = "0.18"
heck = "0.5"
human-panic = "1.2"
indicatif = { version = "0.17", features = ["improved_unicode", "rayon"] }
itertools = "0.12"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
parking_lot = "0.12"
quork = "0.6"
rayon = "1.10"
regex = "1.10"
reqwest = { version = "0.12", features = ["blocking"] }
scoop-manifest-hash = { version = "0.1.0", path = "crates/manifest-hash", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "./crates/derive" }
shadow-rs = "0.27"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
url = { version = "2.5" }
which = "6.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
shadow-rs = "0.27"
