[package]
edition = "2021"
license = { workspace = true }
name = "sprinkles"
publish.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["info-difftrees", "manifest-hashes"]
info-difftrees = []
manifest-hashes = ["base64", "quick-xml", "serde_json_path"]
v2 = []

[dependencies]
anyhow = "1.0"
base64 = { version = "0.22.0", optional = true }
cfg-if = "1.0"
chrono.workspace = true
clap = "4.5"
colored = "2.1"
const-str = { version = "0.5", features = ["all"] }
derive_more = "0.99"
digest = { version = "0.10.7", features = ["std"] }
directories = "5.0"
dunce = "1.0"
getset = "0.1.2"
git2.workspace = true
heck = "0.5"
indicatif = { version = "0.17", features = ["improved_unicode", "rayon"] }
itertools = "0.12"
log.workspace = true
md-5 = "0.10.6"
owo-colors.workspace = true
quick-xml = { version = "0.31.0", optional = true, features = ["serialize"] }
quork = "0.6"
rayon = "1.10"
regex = "1.10"
reqwest = { version = "0.12", features = ["blocking"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_json_path = { version = "0.6.7", optional = true }
sfsu-derive = { path = "../derive" }
sha1 = "0.10.6"
sha2 = "0.10.8"
strum = { version = "0.26", features = ["derive"] }
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
thiserror = "1.0"
tokio = { version = "1.37.0", features = [
    "fs",
    "macros",
    "parking_lot",
    "time",
] }
url = { version = "2.5.0", features = ["serde"] }
urlencoding = "2.1.3"
which = "6.0"
windows = { version = "0.56", features = ["Win32_Storage_FileSystem"] }
windows-version = "0.1.1"
winreg = "0.52"
