[package]
edition = "2021"
name = "sprinkles"
publish = { workspace = true }
version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["info-difftrees"]
info-difftrees = []
v2 = []

[dependencies]
anyhow = "1.0"
chrono = { version = ">=0.4.37", features = [
    "clock",
    "serde",
    "std",
], default-features = false }
clap = { version = "4.5", features = ["derive"] }
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
git2 = "0.18"
heck = "0.5"
indicatif = { version = "0.17", features = ["improved_unicode", "rayon"] }
itertools = "0.12"
log = { version = "0.4", features = ["std"] }
owo-colors = { workspace = true }
quork = { workspace = true }
rayon = "1.10"
regex = "1.10"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
which = "6.0"
windows = { version = "0.56", features = ["Win32_Storage_FileSystem"] }
windows-version = "0.1.1"
winreg = "0.52"
