name: Build & Test

on:
  pull_request:
    branches:
      - 'trunk'

  push:
    branches:
      - 'trunk'

    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0

      - name: Install i686 GCC
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64 -y

      - name: Install latest stable
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Update toolchains
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-pc-windows-gnu

      - name: Build and Package
        shell: pwsh
        run: ./generate-release.ps1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: package.zip
          path: release/*

      - name: Upload & Publish
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*.7z*

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            release/*.7z$

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, i686-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v3

      - name: Install latest stable
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Update toolchains
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build and Test
        run: cargo test --target ${{ matrix.target }}
