name: Build & Test

on:
  workflow_call:

  pull_request:
    branches:
      - 'trunk'

  push:
    branches:
      - 'trunk'
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup.yml
        name: Setup workflow

      - name: Build and Package
        shell: pwsh
        run: ./generate-release.ps1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: package.zip
          path: release/*

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup.yml
        name: Setup workflow

      - name: Test
        run: |
          cargo test --target x86_64-pc-windows-gnu
          cargo test --target i686-pc-windows-gnu
