name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build.yml
        name: Build and Package

      - name: Upload & Publish
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: release/*.7z*

      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v3
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            release/*.7z$
