name: Scan Release

on:
  release:
    types: [published, edited]

jobs:
  scan:
    name: Scan Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            release/dl-i686.7z
            release/dl-x86_64.7z
