name: Setup Workflow Environment

on:
  workflow_call:

jobs:
  setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2.2.0

      - name: Install i686 GCC
        run: sudo apt-get update && sudo apt-get install gcc-mingw-w64 -y

      - name: Install latest stable
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Update toolchains
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add i686-pc-windows-gnu
